# Places to visit in the future
future_trips =  ['italy', 'frence', 'portugal', 'grece', 'egypt']
print(future_trips)
print()
# sorting alphabetically order (temporarily)
print(sorted(future_trips))
print(future_trips)
print()
# sorting alphabetically order in reverse (temporarily)
print(sorted(future_trips, reverse=True))
print(future_trips)
print()

# reverse order (permanently)
future_trips.reverse()
print(future_trips)
future_trips.reverse()
print(future_trips)
print()

# sorting the order (permanently)
future_trips.sort()
print(future_trips)
future_trips.sort(reverse=True)
print(future_trips)