print()
guest_list = ['Maize','Chico Melo','Taty']
msg = 'I would love to invite you, {}, for dinner with me.'

print(msg.format(guest_list[0]))
print(msg.format(guest_list[1]))
print(msg.format(guest_list[2]))
print()
print('Unfortunately, just found out that {} can not make it.'.format(guest_list[0]))
print()
guest_list[0] = 'Isis'
print(guest_list)
print()
print(msg.format(guest_list[0]))
print(msg.format(guest_list[1]))
print(msg.format(guest_list[2]))
print()
print('It is with pride that I am anouncing that I got a bigger table, and I will add more dear guests to the list!')
print()
guest_list.insert(0, 'Sana')
guest_list.insert(2, 'Beto')
guest_list.insert(-1, 'Alysson')
print('And this is my new list:', guest_list)
print()
print(msg.format(guest_list[0]))
print(msg.format(guest_list[1]))
print(msg.format(guest_list[2]))
print(msg.format(guest_list[3]))
print(msg.format(guest_list[4]))
print(msg.format(guest_list[5]))
print()